import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { complianceAttendanceApi, type ComplianceAttendanceRow } from '../api/complianceAttendance';
import { useAuth } from '../store/auth';
import { fmtNumber } from '../lib/format';
import {
  ComplianceAttendancePanel,
  type ShiftFilter,
} from '../components/compliance/ComplianceAttendancePanel';
import { ComplianceOverrideModal } from '../components/compliance/ComplianceOverrideModal';
import { FinancialReportModal } from '../components/compliance/FinancialReportModal';

const ORG_ADMIN_SHIFT_LABELS = {
  all: 'All',
  A: 'Morning Shift',
  B: 'Afternoon Shift',
  C: 'Night Shift',
};

export function Adjustments() {
  const user = useAuth((s) => s.user);
  const isOrgAdmin = user?.role === 'org.admin';

  const [editRow, setEditRow] = useState<ComplianceAttendanceRow | null>(null);
  const [financialOpen, setFinancialOpen] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ['compliance-attendance', { search: '', date: '', shiftFilter: 'all', page: 1, sortBy: undefined, sortDir: 'asc' }],
    queryFn: () => complianceAttendanceApi.list({ page: 1, pageSize: 1 }),
  });

  const total = data?.total ?? 0;

  return (
    <div>
      <div className="mb-3 flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold">Compliance Adjustments</h1>
          <div className="text-sm text-text-muted">
            {isLoading
              ? 'Loading attendance records…'
              : `${fmtNumber(total)} record${total === 1 ? '' : 's'} · Org admin can override autogenerated 8-hour records`}
          </div>
        </div>
      </div>

      <ComplianceAttendancePanel
        mode={isOrgAdmin ? 'editable' : 'readonly'}
        shiftLabels={ORG_ADMIN_SHIFT_LABELS}
        showStatsScopeHint
        onEditRow={isOrgAdmin ? (row) => setEditRow(row) : undefined}
        emptyDefaultMessage="No compliance attendance records yet."
        tableToolbar={({ shiftFilter }: { shiftFilter: ShiftFilter }) =>
          isOrgAdmin && shiftFilter === 'all' ? (
            <button type="button" className="btn-primary btn-sm" onClick={() => setFinancialOpen(true)}>
              Download Financial Report
            </button>
          ) : null
        }
      />

      {editRow && (
        <ComplianceOverrideModal row={editRow} onClose={() => setEditRow(null)} />
      )}

      {financialOpen && (
        <FinancialReportModal onClose={() => setFinancialOpen(false)} />
      )}
    </div>
  );
}
