import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { ComplianceShift } from '@mams/types';
import { complianceAttendanceApi } from '../api/complianceAttendance';
import { fmtDate, fmtNumber } from '../lib/format';
import { useTimeDisplay } from '../store/timeFormat';
import { alternateShiftLabel } from '../lib/shiftAutogeneration';
import { MobileFilterBar } from '../components/ui/MobileFilterBar';

const SHIFT_FILTERS: { id: 'all' | ComplianceShift; label: string }[] = [
  { id: 'all', label: 'All shifts' },
  { id: 'A', label: 'Morning' },
  { id: 'B', label: 'Afternoon' },
  { id: 'C', label: 'Night' },
];

export function ComplianceAttendanceLog() {
  const { fmtTime } = useTimeDisplay();
  const qc = useQueryClient();
  const [search, setSearch] = useState('');
  const [date, setDate] = useState('');
  const [shiftFilter, setShiftFilter] = useState<'all' | ComplianceShift>('all');
  const [page, setPage] = useState(1);
  const pageSize = 50;

  const { data, isLoading, refetch } = useQuery({
    queryKey: ['compliance-attendance', { search, date, shiftFilter, page }],
    queryFn: () =>
      complianceAttendanceApi.list({
        search: search.trim() || undefined,
        date: date || undefined,
        alternateShift: shiftFilter === 'all' ? undefined : shiftFilter,
        page,
        pageSize,
      }),
  });

  const generateMutation = useMutation({
    mutationFn: () => complianceAttendanceApi.generate(date || undefined),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['compliance-attendance'] });
    },
  });

  const items = data?.items ?? [];
  const total = data?.total ?? 0;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="text-xl font-bold text-text">Compliance Attendance</h1>
          <p className="text-sm text-text-muted mt-1">
            Autogenerated 8-hour clock-in/out (Morning → Afternoon → Night). Independent of real punches and leave.
          </p>
        </div>
        <button
          type="button"
          className="btn-primary text-sm px-4 py-2 shrink-0"
          disabled={generateMutation.isPending}
          onClick={() => generateMutation.mutate()}
        >
          {generateMutation.isPending ? 'Generating…' : 'Generate for date'}
        </button>
      </div>

      {generateMutation.isSuccess && (
        <div className="card p-3 text-sm text-green-on-bg bg-green-bg">
          Generated {generateMutation.data.generated} records for {generateMutation.data.date}
          {generateMutation.data.skippedSunday ? ' (Sunday skipped)' : ''}.
        </div>
      )}

      {generateMutation.isError && (
        <div className="card p-3 text-sm text-red bg-red-bg">
          Generation failed. Try again or pick a weekday date filter.
        </div>
      )}

      <MobileFilterBar
        search={search}
        onSearchChange={(v) => {
          setSearch(v);
          setPage(1);
        }}
        searchPlaceholder="Search employee, code, department…"
        date={date}
        onDateChange={(v) => {
          setDate(v);
          setPage(1);
        }}
        onClear={() => {
          setSearch('');
          setDate('');
          setShiftFilter('all');
          setPage(1);
        }}
        isModified={Boolean(search.trim() || date || shiftFilter !== 'all')}
      />

      <div className="flex flex-wrap gap-2">
        {SHIFT_FILTERS.map((f) => (
          <button
            key={f.id}
            type="button"
            className={`px-3 py-1.5 rounded-full text-xs font-medium border ${
              shiftFilter === f.id
                ? 'bg-accent text-accent-fg border-accent'
                : 'bg-surface border-border text-text-muted'
            }`}
            onClick={() => {
              setShiftFilter(f.id);
              setPage(1);
            }}
          >
            {f.label}
          </button>
        ))}
      </div>

      <div className="hidden md:block card overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border text-left text-text-muted text-xs uppercase tracking-wide">
              <th className="p-3">Date</th>
              <th className="p-3">Employee</th>
              <th className="p-3">Code</th>
              <th className="p-3">Department</th>
              <th className="p-3">Shift</th>
              <th className="p-3">Clock-in</th>
              <th className="p-3">Clock-out</th>
              <th className="p-3">Hours</th>
              <th className="p-3">Status</th>
            </tr>
          </thead>
          <tbody>
            {isLoading ? (
              <tr>
                <td colSpan={9} className="p-6 text-center text-text-muted">
                  Loading…
                </td>
              </tr>
            ) : items.length === 0 ? (
              <tr>
                <td colSpan={9} className="p-6 text-center text-text-muted">
                  No compliance attendance yet. Use Generate or wait for nightly autogen at 00:00 IST.
                </td>
              </tr>
            ) : (
              items.map((row) => (
                <tr key={row._id} className="border-b border-border/60 hover:bg-surface-alt/50">
                  <td className="p-3 font-mono">{fmtDate(row.date)}</td>
                  <td className="p-3">{row.employeeId?.name ?? '—'}</td>
                  <td className="p-3 font-mono text-text-muted">{row.employeeId?.empCode ?? '—'}</td>
                  <td className="p-3">{row.employeeId?.department ?? '—'}</td>
                  <td className="p-3">{alternateShiftLabel(row.alternateShift)}</td>
                  <td className="p-3 font-mono">{fmtTime(row.checkInAt)}</td>
                  <td className="p-3 font-mono">
                    {fmtTime(row.checkOutAt)}
                    {row.checkOutNextDay ? ' (+1)' : ''}
                  </td>
                  <td className="p-3 font-mono">{row.hoursWorked.toFixed(2)}</td>
                  <td className="p-3">
                    <span className="px-2 py-0.5 rounded text-[10px] font-semibold bg-green-bg text-green-on-bg">
                      {row.status}
                    </span>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div className="md:hidden space-y-2">
        {isLoading ? (
          <div className="card p-4 text-center text-text-muted text-sm">Loading…</div>
        ) : items.length === 0 ? (
          <div className="card p-4 text-center text-text-muted text-sm">No records yet.</div>
        ) : (
          items.map((row) => (
            <div key={row._id} className="card p-4 space-y-2 text-sm">
              <div className="flex justify-between gap-2">
                <span className="font-semibold">{row.employeeId?.name}</span>
                <span className="font-mono text-text-muted">{fmtDate(row.date)}</span>
              </div>
              <div className="text-text-muted text-xs">
                {row.employeeId?.empCode} · {row.employeeId?.department}
              </div>
              <div>{alternateShiftLabel(row.alternateShift)}</div>
              <div className="flex justify-between font-mono text-xs">
                <span>In {fmtTime(row.checkInAt)}</span>
                <span>
                  Out {fmtTime(row.checkOutAt)}
                  {row.checkOutNextDay ? ' (+1)' : ''}
                </span>
              </div>
              <div className="text-xs">{row.hoursWorked.toFixed(2)} h · {row.status}</div>
            </div>
          ))
        )}
      </div>

      {total > pageSize && (
        <div className="flex items-center justify-between text-sm text-text-muted">
          <span>
            {fmtNumber(total)} records · page {page} of {totalPages}
          </span>
          <div className="flex gap-2">
            <button
              type="button"
              className="btn-secondary px-3 py-1 text-xs"
              disabled={page <= 1}
              onClick={() => setPage((p) => Math.max(1, p - 1))}
            >
              Previous
            </button>
            <button
              type="button"
              className="btn-secondary px-3 py-1 text-xs"
              disabled={page >= totalPages}
              onClick={() => setPage((p) => p + 1)}
            >
              Next
            </button>
          </div>
        </div>
      )}

      <button type="button" className="sr-only" onClick={() => refetch()}>
        Refresh
      </button>
    </div>
  );
}
