import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { complianceAttendanceApi } from '../api/complianceAttendance';
import { fmtNumber } from '../lib/format';
import { ComplianceAttendancePanel } from '../components/compliance/ComplianceAttendancePanel';
import { ComplianceReportModal } from '../components/compliance/ComplianceReportModal';

const REPORT_DEFAULT_MONTH = '2026-05';

export function ComplianceAttendanceLog() {
  const [reportOpen, setReportOpen] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ['compliance-attendance', { search: '', date: '', shiftFilter: 'all', page: 1, sortBy: undefined, sortDir: 'asc' }],
    queryFn: () => complianceAttendanceApi.list({ page: 1, pageSize: 1 }),
  });

  const total = data?.total ?? 0;

  const headerActions = (
    <button type="button" className="btn-outline btn-sm shrink-0" onClick={() => setReportOpen(true)}>
      Generate report
    </button>
  );

  const mobileReportButton = (
    <button type="button" className="btn-outline btn-sm shrink-0" onClick={() => setReportOpen(true)}>
      Report
    </button>
  );

  return (
    <div>
      <div className="mb-3 flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold">Attendance Log</h1>
          <div className="text-sm text-text-muted">
            {isLoading
              ? 'Loading attendance records…'
              : data
                ? `${fmtNumber(total)} record${total === 1 ? '' : 's'}`
                : 'Autogenerated 8-hour attendance (Morning → Afternoon → Night).'}
          </div>
        </div>
        <div className="hidden md:flex items-center gap-2 shrink-0 flex-wrap justify-end">
          {headerActions}
        </div>
      </div>

      <ComplianceAttendancePanel
        mode="readonly"
        showGenerateActions
        showStatsScopeHint
        headerActions={mobileReportButton}
      />

      {reportOpen && (
        <ComplianceReportModal
          initialYearMonth={REPORT_DEFAULT_MONTH}
          onClose={() => setReportOpen(false)}
        />
      )}
    </div>
  );
}
