import { Router } from 'express';
import authRoutes from './auth.routes.js';
import employeesRoutes from './employees.routes.js';
import attendanceRoutes from './attendance.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import adjustmentsRoutes from './adjustments.routes.js';
import employeeChangeRequestsRoutes from './employeeChangeRequests.routes.js';
import devicesRoutes from './devices.routes.js';
import settingsRoutes from './settings.routes.js';
import reportsRoutes from './reports.routes.js';
import usersRoutes from './users.routes.js';
import csvImportRoutes from './csvImport.routes.js';
import goLiveRoutes from './goLive.routes.js';
import activityRoutes from './activity.routes.js';
import leaveRoutes from './leave.routes.js';
import regularizationRoutes from './regularization.routes.js';
import visitorsRoutes from './visitors.routes.js';
import adminRoutes from './admin.routes.js';
import adminOverviewRoutes from './adminOverview.routes.js';
import complianceAttendanceRoutes from './complianceAttendance.routes.js';

export const apiRouter = Router();
apiRouter.use('/auth', authRoutes);
apiRouter.use('/employees', employeesRoutes);
apiRouter.use('/employees/import-csv', csvImportRoutes);
apiRouter.use('/attendance', attendanceRoutes);
apiRouter.use('/compliance-attendance', complianceAttendanceRoutes);
apiRouter.use('/dashboard', dashboardRoutes);
apiRouter.use('/adjustments', adjustmentsRoutes);
apiRouter.use('/employee-change-requests', employeeChangeRequestsRoutes);
apiRouter.use('/devices', devicesRoutes);
apiRouter.use('/settings', settingsRoutes);
apiRouter.use('/reports', reportsRoutes);
apiRouter.use('/users', usersRoutes);
apiRouter.use('/go-live', goLiveRoutes);
apiRouter.use('/activity', activityRoutes);
apiRouter.use('/leave', leaveRoutes);
apiRouter.use('/regularization', regularizationRoutes);
apiRouter.use('/visitors', visitorsRoutes);
apiRouter.use('/admin', adminRoutes);
apiRouter.use('/admin/overview', adminOverviewRoutes);

apiRouter.get('/health', (_req, res) => {
  res.json({ status: 'ok', ts: new Date().toISOString() });
});
