module.exports = {
  apps: [
    {
      name: 'mams-server',
      cwd: '/opt/mams/current/mams-server',
      script: 'dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        VOSK_SERVICE_URL: 'http://127.0.0.1:8765',
        VOSK_MODELS_DIR: '/opt/mams/current/mams-server/vosk-models',
      },
      out_file: '/var/log/mams/server.log',
      error_file: '/var/log/mams/server-error.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mams-vosk',
      cwd: '/opt/mams/current/mams-server/vosk-service',
      script: '/opt/mams/vosk-venv/bin/uvicorn',
      args: 'app:app --host 127.0.0.1 --port 8765',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '768M',
      env: {
        VOSK_MODELS_DIR: '/opt/mams/current/mams-server/vosk-models',
        VOSK_HOST: '127.0.0.1',
        VOSK_PORT: '8765',
      },
      out_file: '/var/log/mams/vosk.log',
      error_file: '/var/log/mams/vosk-error.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
