export const TABLE_COLUMN_TOOLTIPS = {
  employees: {
    empCode: 'Unique employee code used in reports and device mapping.',
    name: 'Employee full name as stored in HR records.',
    department: 'Assigned department or cost center.',
    location: 'Work location or site.',
    joinDate: 'Date the employee joined the organization.',
    status: 'Active, inactive, or other employment status.',
    biometricId: 'ID string sent by the biometric device for this employee.',
  },
  leave: {
    employee: 'Employee who submitted the leave request.',
    fromDate: 'First day of leave.',
    toDate: 'Last day of leave.',
    totalDays: 'Working days consumed by this request.',
    status: 'Pending, approved, rejected, or cancelled.',
    leaveType: 'Category of leave (paid, casual, sick, etc.).',
    name: 'Display name of the leave type or holiday.',
    paid: 'Whether this leave type counts as paid leave.',
    halfDayEligible: 'Whether half-day requests are allowed for this type.',
    annualQuotaDefault: 'Default annual quota in days for new employees.',
    active: 'Whether this leave type can be selected for new requests.',
    date: 'Calendar date of the holiday.',
    type: 'National, restricted, or other holiday classification.',
  },
  attendance: {
    rawTimestamp: 'Exact punch time from the device (IST).',
    name: 'Employee name at time of punch.',
    empCode: 'Employee code linked to the punch.',
    id: 'Employee code.',
    dept: 'Employee department.',
    shift: 'Assigned time shift for the day.',
    hrs: 'Total hours worked for the selected date.',
    punchType: 'Check-in, check-out, or other punch type.',
    shiftWindowLabel: 'Assigned shift window for this punch.',
    device: 'Biometric device that recorded the punch.',
    when: 'Date and time of the orphan punch.',
    entry: 'First check-in time for the day.',
    exit: 'Last check-out time for the day.',
  },
  reports: {
    date: 'Attendance date for the row.',
    code: 'Employee code.',
    name: 'Employee name.',
    department: 'Department for the employee.',
    location: 'Work location.',
    entry: 'First check-in time for the day.',
    exit: 'Last check-out time for the day.',
    hours: 'Net hours worked for the day.',
    ot: 'Overtime hours beyond the standard shift.',
    status: 'Attendance status for the day.',
    present: 'Days marked present in the period.',
    absent: 'Days marked absent in the period.',
    weeklyOff: 'Scheduled weekly off days in the period.',
    totalHrs: 'Total hours worked in the period.',
    equivDays: 'Equivalent present days based on hours.',
    employees: 'Headcount in the department.',
    avgHrs: 'Average hours per employee in the period.',
  },
  compliance: {
    date: 'Compliance attendance date.',
    name: 'Employee name on the compliance record.',
    empCode: 'Employee code on the compliance record.',
    department: 'Employee department.',
    alternateShift: 'Alternate shift assigned for compliance view.',
    hoursWorked: 'Hours worked on the compliance record.',
    status: 'Compliance attendance status for the day.',
  },
  visitors: {
    submitted: 'When the visitor form was submitted.',
    status: 'Approval or visit status.',
    validUntil: 'Last date the visit request remains valid.',
  },
  devices: {
    name: 'Device display name.',
    location: 'Physical location of the device.',
    online: 'Whether the device responded on the last sync.',
    lastSync: 'Last successful sync with the server.',
    punches24h: 'Punch events received in the last 24 hours.',
  },
  audit: {
    occurredAt: 'When the event occurred (IST).',
    eventType: 'Category of audit or activity event.',
    area: 'Application area where the event occurred.',
    user: 'User who performed the action.',
    event: 'Summary of the feature flag or config change.',
    when: 'Timestamp of the change.',
  },
  settings: {
    name: 'User display name.',
    email: 'Sign-in email address.',
    role: 'Assigned role and permissions.',
    status: 'Whether the account is active.',
    lastLogin: 'Most recent successful sign-in.',
    user: 'User who performed the action or owns the record.',
  },
  changeRequests: {
    changeType: 'Type of employee change requested.',
    initiatedBy: 'User who submitted the request.',
    initiatedAt: 'When the request was submitted.',
    status: 'Pending, approved, or rejected.',
  },
} as const;

export type TableColumnModule = keyof typeof TABLE_COLUMN_TOOLTIPS;

export function tableColumnTooltip(
  module: TableColumnModule,
  column: string
): string | undefined {
  const map = TABLE_COLUMN_TOOLTIPS[module] as Record<string, string>;
  return map[column];
}
