import type { CompanyBranding } from './companyBranding';

export type ReportPrintColumn = {
  key: string;
  label: string;
  mono?: boolean;
};

export type ReportPrintOptions = {
  branding: CompanyBranding;
  title: string;
  subtitle?: string;
  summaryLine?: string;
  columns: ReportPrintColumn[];
  rows: Record<string, string | number>[];
  signatoryOnLastPage?: boolean;
};

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function escapeCssString(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ');
}

function formatGeneratedAt(): string {
  return new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });
}

function renderTableRows(
  columns: ReportPrintColumn[],
  rows: Record<string, string | number>[]
): string {
  return rows
    .map((row) => {
      const cells = columns
        .map((col) => {
          const raw = row[col.key];
          const value = raw === undefined || raw === null || raw === '' ? '—' : String(raw);
          const cls = [
            col.mono ? 'mono' : '',
            col.key === 'status' && value === 'Present' ? 'status-present' : '',
            col.key === 'status' && value === 'Absent' ? 'status-absent' : '',
          ]
            .filter(Boolean)
            .join(' ');
          return `<td${cls ? ` class="${cls}"` : ''}>${escapeHtml(value)}</td>`;
        })
        .join('');
      return `<tr>${cells}</tr>`;
    })
    .join('');
}

function renderSignatory(branding: CompanyBranding): string {
  if (!branding.signatoryName.trim()) return '';
  const designation = branding.signatoryDesignation.trim() || 'Authorized Signatory';
  return `
    <div class="signatory-block">
      <div class="signatory-line">${escapeHtml(branding.signatoryName)}</div>
      <div class="signatory-desig">${escapeHtml(designation)}</div>
    </div>
    <div class="generated-by">Generated by MAMS</div>
  `;
}

export function buildReportPrintHtml(options: ReportPrintOptions): string {
  const {
    branding,
    title,
    subtitle,
    summaryLine,
    columns,
    rows,
    signatoryOnLastPage = true,
  } = options;

  const logoHtml = branding.companyLogo
    ? `<img class="logo-img" src="${escapeHtml(branding.companyLogo)}" alt="Company logo" />`
    : '';

  const footerConfidentialityHtml =
    branding.confidentialityNoticeEnabled && branding.confidentialityNoticeText.trim()
      ? `<div class="footer-confidentiality">${escapeHtml(branding.confidentialityNoticeText)}</div>`
      : '';

  const headerCells = columns.map((c) => `<th>${escapeHtml(c.label)}</th>`).join('');
  const bodyRows = renderTableRows(columns, rows);

  const signatoryHtml = signatoryOnLastPage ? renderSignatory(branding) : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: "Segoe UI", Arial, sans-serif;
      color: #1a1f36;
      background: #fff;
      padding: 88px 0 52px;
    }
    .letterhead-fixed {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      z-index: 1000;
      background: #fff;
      border-bottom: 1px solid #e2e6ed;
      padding: 10px 12mm 8px;
    }
    .logo-row {
      display: flex;
      align-items: flex-start;
      gap: 12px;
    }
    .logo-img {
      width: 50px;
      height: 50px;
      object-fit: contain;
      border-radius: 6px;
      border: 1px solid #e2e6ed;
      padding: 3px;
      background: #fff;
      flex-shrink: 0;
    }
    .company-name {
      font-size: 14px;
      font-weight: 700;
      color: #1a1f36;
      line-height: 1.25;
    }
    .company-address {
      font-size: 9px;
      color: #4e5d78;
      margin-top: 3px;
      white-space: pre-line;
      line-height: 1.35;
    }
    .footer-fixed {
      position: fixed;
      bottom: 0;
      left: 0;
      right: 0;
      z-index: 1000;
      background: #fff;
      border-top: 1px solid #4e5d78;
      padding: 6px 12mm 4px;
      min-height: 28px;
    }
    .footer-confidentiality {
      text-align: center;
      font-size: 8pt;
      font-style: italic;
      color: #8492a6;
      line-height: 1.35;
    }
    .content {
      padding: 0 12mm;
    }
    .report-title {
      font-size: 15px;
      font-weight: 700;
      color: #1A2878;
      margin-bottom: 4px;
    }
    .report-subtitle {
      font-size: 10px;
      color: #4e5d78;
      margin-bottom: 6px;
    }
    .report-summary {
      font-size: 10px;
      color: #4e5d78;
      margin-bottom: 12px;
    }
    .report-generated {
      font-size: 10px;
      color: #8492a6;
      margin-bottom: 12px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 10px;
      margin-top: 6px;
    }
    thead { display: table-header-group; }
    th {
      background: #1A2878;
      color: #fff;
      padding: 6px 8px;
      text-align: left;
      font-size: 9px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    td {
      padding: 5px 8px;
      border-bottom: 1px solid #e2e6ed;
    }
    tr:nth-child(even) td { background: #f8f9fb; }
    .mono { font-family: Consolas, "Courier New", monospace; font-size: 10px; }
    .status-present { color: #4a7a16; font-weight: 600; }
    .status-absent { color: #E82C2C; font-weight: 600; }
    .signatory-block {
      margin-top: 28px;
      width: 180px;
    }
    .signatory-line {
      border-top: 1px solid #4e5d78;
      padding-top: 4px;
      font-weight: 600;
      font-size: 10px;
      color: #1a1f36;
    }
    .signatory-desig {
      color: #8492a6;
      font-size: 9px;
      margin-top: 2px;
    }
    .generated-by {
      margin-top: 16px;
      font-size: 9px;
      color: #8492a6;
      text-align: right;
    }
    @page {
      size: A4 landscape;
      margin: 22mm 12mm 20mm 12mm;
      @bottom-right {
        content: "Page " counter(page) " of " counter(pages);
        font-size: 9pt;
        color: #8492a6;
      }
    }
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
  </style>
</head>
<body>
  <div class="letterhead-fixed">
    <div class="logo-row">
      ${logoHtml}
      <div>
        <div class="company-name">${escapeHtml(branding.companyName)}</div>
        ${branding.registeredAddress ? `<div class="company-address">${escapeHtml(branding.registeredAddress)}</div>` : ''}
      </div>
    </div>
  </div>

  <div class="footer-fixed">
    ${footerConfidentialityHtml}
  </div>

  <div class="content">
    <div class="report-title">${escapeHtml(title)}</div>
    ${subtitle ? `<div class="report-subtitle">${escapeHtml(subtitle)}</div>` : ''}
    <div class="report-generated">Generated: ${formatGeneratedAt()}</div>
    ${summaryLine ? `<div class="report-summary">${escapeHtml(summaryLine)}</div>` : ''}
    <table>
      <thead><tr>${headerCells}</tr></thead>
      <tbody>${bodyRows}</tbody>
    </table>
    ${signatoryHtml}
  </div>

  <script>
    window.onload = function () {
      setTimeout(function () { window.print(); }, 400);
    };
  <\/script>
</body>
</html>`;
}

/** Opens print dialog directly via a hidden iframe (no extra browser tab). */
export function openReportPrintWindow(options: ReportPrintOptions): boolean {
  const html = buildReportPrintHtml(options);
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  try {
    const iframe = document.createElement('iframe');
    iframe.setAttribute('title', 'Report print');
    iframe.style.cssText =
      'position:fixed;width:0;height:0;border:0;opacity:0;pointer-events:none;left:-9999px';
    document.body.appendChild(iframe);

    const cleanup = () => {
      iframe.remove();
      URL.revokeObjectURL(url);
    };

    iframe.onload = () => {
      const win = iframe.contentWindow;
      if (!win) {
        cleanup();
        return;
      }
      const onAfterPrint = () => {
        win.removeEventListener('afterprint', onAfterPrint);
        cleanup();
      };
      win.addEventListener('afterprint', onAfterPrint);
      setTimeout(() => {
        win.focus();
        win.print();
        setTimeout(cleanup, 120_000);
      }, 300);
    };

    iframe.src = url;
    return true;
  } catch {
    URL.revokeObjectURL(url);
    return false;
  }
}
